# do hyprctl monitors to find your-monitor

# wallpaper {
#     monitor = your-monitor 
#     # path = ~/.config/hypr/bgs/peakpower.png
#     # path = ~/.config/hypr/bgs/peakbeni.png
#     # path = ~/.config/hypr/bgs/nerv.png
#     # path = ~/.config/hypr/bgs/peaklain.png
#     # path = ~/.config/hypr/bgs/asayoru.png
#     path = ~/.config/hypr/bgs/lainbmp.png
#     fit_mode = cover
# }

wallpaper {
    monitor = HDMI-A-2
    # path = ~/.config/hypr/bgs/peakpower.png
    # path = ~/.config/hypr/bgs/peakbeni.png
    # path = ~/.config/hypr/bgs/nerv.png
    # path = ~/.config/hypr/bgs/peaklain.png
    # path = ~/.config/hypr/bgs/asayoru.png
    path = ~/.config/hypr/bgs/lainbmp.png
    fit_mode = cover
}

splash = false
